version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
    delete:
      enabled: true
auth:
  token:
    realm: https://portus.staging.teco.edu/v2/token
    service: portus.staging.teco.edu
    issuer: portus.staging.teco.edu
    rootcertbundle: /certs/fullchain.pem
http:
  addr: :5000
  host: portus.staging.teco.edu:5000
  tls:
    certificate: /certs/fullchain.pem
    key: /certs/privkey.pem
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
notifications:
  endpoints:
    - name: portus
      url: https://portus.staging.teco.edu/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
